apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-$USER
  namespace: decice
  labels:
    app: publisher-$USER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher-$USER
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - image: cn04:30500/$USER-publisher:latest
          name: publisher
          imagePullPolicy: IfNotPresent
          env:
            - name: BROKER_ADDRESS
              value: "localhost"
            - name: TOPIC
              value: "decice"
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service
metadata:
  namespace: decice
  name: publisher-$USER
  labels:
    name: publisher-$USER
spec:
  ports:
    - port: 4000
      name: http-4000
      protocol: TCP
  selector:
    app: publisher-$USER
  type: ClusterIP
